name: ${project.artifactId}
main: com.mcmiddleearth.mcmechat.ChatPlugin
version: ${project.version}
author: Eriol_Eandur
softdepend: [Tab, DiscordSRV]
depend: [Essentials, LuckPerms, PlaceholderAPI, PluginUtils]
api-version: 1.15

commands:
   mcmechat:
      description: reloads config file
      usage: /mcmechat reload
   helper:
      description: configurable help command
      usage: /helper <topic>
   history:
      description: manage history entries of a player
      usage: /history <playername> add|insert|remove|show
   report:
      description: file a report to the moderation team
      usage: /report <message>
   namehistory:
      description: get a player's minecraft name history
      usage: /namehistory <playername> <page>
permissions:
    mcmechat.reporter:
        default: op
        descroption: Allows to use /report command
    mcmechat.reload:
        description: Allows to use reload config using /mcmechat reload
        default: op
    mcmechat.history:
        description: Allows to use /history command
        default: op
    mcmechat.helper.info:
        description: Allows to use /helper command
        default: true
